#default configuration
configuration:  
  projectName: treasure
server:
  port: 80
message:
  greeting: Hello from the configuration!
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:  
  routes:
    cats:
      url: http://cat-service:9000
      path: /cats/**
      stripPrefix: false
    dogs:
      url: http://dog-service:9001
      path: /dogs/**
      stripPrefix: false
---
spring:  
  profiles: dev
server:  
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:  
  routes:
    cats:
      url: http://localhost:9000
      path: /cats/**
      stripPrefix: false
    dogs:
      url: http://localhost:9001
      path: /dogs/**
      stripPrefix: false
debug: true
